version: 2
jobs:
        - build:
                  docker:
                          - image: cirrusci/flutter
                            steps:
                                    - checkout
                                    - run: flutter -v build apk --target-platform android-arm,android-arm64 --release --split-per-abi

        - upload_artifacts:
                requires:
                        - build
                        - store_artifacts:
                                path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk
                        - store_artifacts:
                                path: build/app/outputs/apk/release/app-arm64-v8a-release.apk
