version: 2
jobs:
        build:
                  branches:
                          only:
                                  - master
                  docker:
                          - image: cirrusci/flutter
                  steps:
                          - checkout
                          - run: flutter -v build apk --target-platform android-arm,android-arm64 --release --split-per-abi
                          - store_artifacts:
                                 path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk
                          - store_artifacts:
                                 path: build/app/outputs/apk/release/app-arm64-v8a-release.apk
                          - run:
                                  command: |
                                          cd ~
                                          git clone https://github.com/uditkarode/FlutterTimeTable -b builds
                                          cd FlutterTimeTable
                                          rm *
                                          cp ~/project/build/app/outputs/apk/release/app-armeabi-v7a-release.apk tt-arm-$(TZ=Asia/Kolkata date +"%Y%m%d").apk
                                          cp ~/project/build/app/outputs/apk/release/app-arm64-v8a-release.apk tt-arm64-$(TZ=Asia/Kolkata date +"%Y%m%d").apk
                                          git config user.email "builder@circle.ci"
                                          git config user.name "BobTheBuilder"
                                          git add .
                                          git commit -m "bot: build installables <$(TZ=Asia/Kolkata date +'%Y%m%d %T')>"
                                          git push -u origin builds
